{{- if and (eq .Values.auth.type "static") (not .Values.auth.static.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalayers-single.authSecretName" . }}
  labels:
    {{- include "datalayers-single.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.static.secretKeys.username }}: {{ .Values.auth.static.username | quote }}
  {{ .Values.auth.static.secretKeys.password }}: {{ .Values.auth.static.password | quote }}
{{- end }}
