apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalayers-single.fullname" . }}
  labels:
    {{- include "datalayers-single.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "datalayers-single.selectorLabels" . | nindent 4 }}
